### PR TITLE
Fix back navigation behavior when tapping a list item in About Screen.

### LINKED ISSUE #644: Fix back navigation behavior in About screen when tapping list items
**Idea Description**

Currently, when tapping a list item in the AboutScreen, a new NavKey is continuously pushed onto the stack. As a result, pressing the back button only pops one NavKey at a time, and it takes multiple presses before the right-side pane is closed.

This issue should be fixed so that tapping a list item opens the right-side pane without stacking redundant NavKeys, and pressing the back button once correctly closes the pane.

https://github.com/user-attachments/assets/353705bd-a96c-4db6-84d7-9fb1a1eecfe2

**Reference images and links**

### PR DESCRIPTION
**Pull request by nyafunta9858**
## Issue
- close #644 

## Overview (Required)
- Fix back navigation behavior when tapping a list item in the About Screen.
  - Currently, the items in the “About” screen opened in the right pane reappear when you tap another item with the same specification and then press the back key.
  - Therefore, fixed to pop the NavKey from the back stack when tapping the About Screen Items if another item with the same specification exists on the back stack. 

## Links
- 

## Screenshot (Optional if screenshot test is present or unrelated to UI)
Before | After
:--: | :--:
 | 

## Movie (Optional)
Before | After
:--: | :--:
record-250911234424 | record-250911234045

### CODE REVIEW

File: app-shared/src/androidJvmMain/kotlin/io/github/droidkaigi/confsched/KaigiAppUi.androidJvm.kt [hunk 1]
```diff
@@ -127,16 +128,24 @@ actual fun KaigiAppUi() {
                         } else {
                             "https://portal.droidkaigi.jp/en"
                         }
+
+                        fun navigateToAboutItem(navKey: AboutItemNavKey) {
+                            if (backStack.lastOrNull() is AboutItemNavKey) {
+                                backStack.removeLastOrNull()
+                            }
+                            backStack.add(navKey)
+                        }
```
Comment (kitakkun) [inline app-shared/src/androidJvmMain/kotlin/io/github/droidkaigi/confsched/KaigiAppUi.androidJvm.kt]: I know there’s a similar logic around `TimetableItemDetailNavKey`, so it might be worth consolidating in the future. That said, this looks good to me for now!

https://github.com/DroidKaigi/conference-app-2025/blob/6f33487524de5547307fdde26994fd18198b3500/app-shared/src/androidJvmMain/kotlin/io/github/droidkaigi/confsched/KaigiAppUi.androidJvm.kt#L87-L92

File: app-shared/src/androidJvmMain/kotlin/io/github/droidkaigi/confsched/navkey/AboutNavKey.kt [hunk 2]
```diff
@@ -8,3 +8,17 @@ data object AboutNavKey : NavKey
 
 @Serializable
 data object LicensesNavKey : NavKey
```
Comment (kitakkun) [inline app-shared/src/androidJvmMain/kotlin/io/github/droidkaigi/confsched/navkey/AboutNavKey.kt]: Would it be reasonable for this to also inherit from AboutItemNavKey? Since #639, LicensesScreen also opens using the list-detail scene.

File: app-shared/src/androidJvmMain/kotlin/io/github/droidkaigi/confsched/KaigiAppUi.androidJvm.kt (hunk 1 above)
Comment (nyafunta9858) [reply app-shared/src/androidJvmMain/kotlin/io/github/droidkaigi/confsched/KaigiAppUi.androidJvm.kt]: Thank you for your review!
For example, do you mean like the following code?
```kt
inline fun <reified Key: NavKey> navigateTo(backStack: SnapshotStateList<NavKey>, navKey: Key) {
    if (backStack.lastOrNull() is Key) {
        backStack.removeLastOrNull()
    }
    backStack.add(navKey)
}

navigateTo(backStack, TimetableItemDetailNavKey(it))
```

File: app-shared/src/androidJvmMain/kotlin/io/github/droidkaigi/confsched/navkey/AboutNavKey.kt (hunk 2 above)
Comment (nyafunta9858) [reply app-shared/src/androidJvmMain/kotlin/io/github/droidkaigi/confsched/navkey/AboutNavKey.kt]: Thank you for your review!
Currently, the Licenses screen is displayed full-screen, so I didn't add it to AboutItemNavKey.
Please let me know if my understanding is incorrect 🙏

File: app-shared/src/androidJvmMain/kotlin/io/github/droidkaigi/confsched/KaigiAppUi.androidJvm.kt (hunk 1 above)
Comment (kitakkun) [reply app-shared/src/androidJvmMain/kotlin/io/github/droidkaigi/confsched/KaigiAppUi.androidJvm.kt]: Yes, that’s basically the idea! Just a small detail: I’d like to have SnapshotStateList as the extension receiver, and it would be better if the function name clearly conveys that the same item never appears consecutively in the navigation stack.

File: app-shared/src/androidJvmMain/kotlin/io/github/droidkaigi/confsched/navkey/AboutNavKey.kt (hunk 2 above)
Comment (kitakkun) [reply app-shared/src/androidJvmMain/kotlin/io/github/droidkaigi/confsched/navkey/AboutNavKey.kt]: The branch might be a bit out of date. Could you please merge the latest main into it? 🙏

File: app-shared/src/androidJvmMain/kotlin/io/github/droidkaigi/confsched/KaigiAppUi.androidJvm.kt (hunk 1 above)
Comment (nyafunta9858) [reply app-shared/src/androidJvmMain/kotlin/io/github/droidkaigi/confsched/KaigiAppUi.androidJvm.kt]: I understand it! I will fix it soon. Please wait for a moment!

Comment (kitakkun) [reply app-shared/src/androidJvmMain/kotlin/io/github/droidkaigi/confsched/KaigiAppUi.androidJvm.kt]: Since launchSingleTop exists in navigation-compose, maybe addSingleTop would be a good equivalent in Nav3? What do you think?

Comment (kitakkun) [reply app-shared/src/androidJvmMain/kotlin/io/github/droidkaigi/confsched/KaigiAppUi.androidJvm.kt]: I briefly thought that in the case of AboutItemNavKey, we might have to cast to AboutItemNavKey to call it, which could make the structure more cumbersome and error-prone.

If we don’t come to a solid conclusion, I think the current approach is perfectly fine. I’ll leave it up to you!

UPDATE:
maybe we can call it like:
```kotlin
backStack.addSingleTop<AboutItemNavKey>(ContributorsNavKey)
```

It looks good to me.

Comment (nyafunta9858) [reply app-shared/src/androidJvmMain/kotlin/io/github/droidkaigi/confsched/KaigiAppUi.androidJvm.kt]: Thank you for your cooperation and great advice 🙏 
I have committed all the changes you pointed out!

**Review by kitakkun — APPROVED** [review]
Looks great! Confirmed it’s working as expected.
Also, thanks for the excellent refactoring of the NavKey logic!

Approving — thank you for your work! 🙏

**Comment by nyafunta9858** [comment]
Thank you for your review!
It was such an exciting contribution experience! 🙏
