### PR TITLE
:sparkles: Implemented Modifier extensions that enable Fling Scroll and CollapsingHeaderLayout integration on the JVM.

### LINKED ISSUE #343: Scrolling with mouse operations does not work in JVM applications.
**Idea Description**

- As shown in the attached video, even when dragging with the mouse, LazyColumn does not scroll in the current JVM application.
- Please fix this so that it scrolls in the same way as on Android/iOS.

**Reference images and links**

https://github.com/user-attachments/assets/a26e3c4e-b21a-4086-a92f-1886ff13838e

### PR DESCRIPTION
**Pull request by Corvus400**
## Issue
- close #343

## Overview (Required)
- Multiple screens have been modified to enable scrolling via mouse drag operations.

### CODE REVIEW

File: core/droidkaigiui/src/commonMain/kotlin/io/github/droidkaigi/confsched/droidkaigiui/session/TimetableList.kt [hunk 1]
```diff
@@ -62,7 +63,7 @@ fun TimetableList(
             state = lazyListState,
             verticalArrangement = Arrangement.spacedBy(12.dp),
             contentPadding = contentPadding + WindowInsets.navigationBars.asPaddingValues(),
-            modifier = modifier,
+            modifier = modifier.enableMouseDragScroll(lazyListState),
```
Comment (Corvus400) [inline core/droidkaigiui/src/commonMain/kotlin/io/github/droidkaigi/confsched/droidkaigiui/session/TimetableList.kt:66]: I didn't want to put a large amount of code unrelated to Android/iOS here, so I separated the processing using expect/actual.

File: feature/about/src/commonMain/kotlin/io/github/droidkaigi/confsched/about/AboutScreen.kt [hunk 2]
```diff
@@ -45,9 +48,11 @@ fun AboutScreen(
         modifier = modifier,
     ) { contentPadding ->
         LazyColumn(
+            state = listState,
             contentPadding = contentPadding + WindowInsets.safeDrawingWithBottomNavBar.excludeTop().asPaddingValues(),
             modifier = Modifier
                 .nestedScroll(scrollBehavior.nestedScrollConnection)
+                .enableMouseDragScroll(listState)
```
Comment (Corvus400) [inline feature/about/src/commonMain/kotlin/io/github/droidkaigi/confsched/about/AboutScreen.kt:55]: Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/259f64e4-a3bd-41ca-8870-099fed221ed9" width="300" > | <video src="https://github.com/user-attachments/assets/91564d8b-0e08-4b22-af39-527956a45066" width="300" >

File: feature/contributors/src/commonMain/kotlin/io/github/droidkaigi/confsched/contributors/ContributorsScreen.kt [hunk 3]
```diff
@@ -45,10 +48,12 @@ fun ContributorsScreen(
         modifier = modifier.testTag(ContributorsScreenTestTag),
     ) { innerPadding ->
         LazyColumn(
+            state = listState,
             contentPadding = innerPadding,
             modifier = Modifier
-                .testTag(ContributorsTestTag)
-                .nestedScroll(scrollBehavior.nestedScrollConnection),
+                .nestedScroll(scrollBehavior.nestedScrollConnection)
+                .enableMouseDragScroll(listState)
```
Comment (Corvus400) [inline feature/contributors/src/commonMain/kotlin/io/github/droidkaigi/confsched/contributors/ContributorsScreen.kt:55]: Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/170169a1-3da9-4bec-b6b6-5f8c3c91af0f" width="300" > | <video src="https://github.com/user-attachments/assets/0172f739-5601-4cbf-a71b-f92517c67860" width="300" >

File: feature/eventmap/src/commonMain/kotlin/io/github/droidkaigi/confsched/eventmap/component/EventMap.kt [hunk 4]
```diff
@@ -26,14 +28,18 @@ const val EventMapItemTestTag = "EventMapItemTestTag:"
...
     onClickReadMore: (url: String) -> Unit,
     contentPadding: PaddingValues,
     modifier: Modifier = Modifier,
 ) {
     LazyColumn(
+        state = listState,
         contentPadding = contentPadding,
-        modifier = modifier.testTag(EventMapLazyColumnTestTag),
+        modifier = modifier
+            .enableMouseDragScroll(listState)
```
Comment (Corvus400) [inline feature/eventmap/src/commonMain/kotlin/io/github/droidkaigi/confsched/eventmap/component/EventMap.kt:41]: Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/eb874c20-eca0-4a64-a7bc-1948b6501e70" width="300" > | <video src="https://github.com/user-attachments/assets/63ee3032-ed2a-4857-ae1d-b6021a84076b" width="300" >

File: feature/staff/src/commonMain/kotlin/io/github/droidkaigi/confsched/staff/StaffScreen.kt [hunk 5]
```diff
@@ -43,8 +46,10 @@ fun StaffScreen(
         modifier = modifier,
     ) { contentPadding ->
         LazyColumn(
+            state = listState,
             modifier = Modifier
                 .nestedScroll(scrollBehavior.nestedScrollConnection)
+                .enableMouseDragScroll(listState)
```
Comment (Corvus400) [inline feature/staff/src/commonMain/kotlin/io/github/droidkaigi/confsched/staff/StaffScreen.kt:52]: Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/4ce0cce0-a48f-4977-b83d-350e40550150" width="300" > | <video src="https://github.com/user-attachments/assets/ada5a88f-b9b4-4472-b3e8-15ad2688f1a4" width="300" >

**Review by mikanIchinose — APPROVED** [review]
Awesome work!!
LGTM
