### PR TITLE
fix: FAB's color on timetable item detail.

### LINKED ISSUE #214: The FAB text color is hard to see.
**Idea Description**

The FAB color changes according to the room color, but the text color and icon color within the FAB have low contrast, making them very difficult to see.
Since the text color and icon color of the FAB are not specified in the design, I think it is necessary to determine the specifications in Figma before making any changes.

Overall, I think the contrast ratio is low, but it is particularly low in Meerkat, and I can no longer see what is written.

**Reference images and links**

[Figma](https://www.figma.com/design/1YjyMBNVLEGcHP4W7UNzDE/DroidKaigi-2025-App-UI?node-id=54901-56232&t=9ZcIhkMIebFKL5gm-4)

Image

https://github.com/user-attachments/assets/5aaf5cd4-74fd-441b-b70a-9679562b2784

### PR DESCRIPTION
**Pull request by hiraike32**
## Issue
- close #214

## Overview (Required)
- I fixed FAB color on TimetableItemDetailScreen.
  - Since Figma did not have color definitions, I made RoomTheme.primaryColor transparent so that the text would be easier to read.
  - RoomTheme.containerColor was too transparent.

## Screenshot (Optional if screenshot test is present or unrelated to UI)
Before | After | Before | After
:--: | :--: | :--: | :--:
Screenshot_20250821_184326 | Screenshot_20250821_184202 | Screenshot_20250821_184332 | Screenshot_20250821_184210 |
Screenshot_20250821_184339 | Screenshot_20250821_184216 | Screenshot_20250821_184345 | Screenshot_20250821_184226
| Screenshot_20250821_184352 | Screenshot_20250821_184242 | | |

### CODE REVIEW

File: feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/components/TimetableItemDetailFloatingMenu.kt [hunk 1]
```diff
@@ -98,14 +100,14 @@ private fun TimetableItemDetailFloatingActionButtonMenu(
     }
 
     val roomTheme = LocalRoomTheme.current
-    val menuItemContainerColor = roomTheme.primaryColor // TODO: use room containerColor
+    val menuItemContainerColor = roomTheme.primaryColor.copy(alpha = 0.5f).compositeOver(Color.Black)
```
Comment (hiraike32) [inline feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/components/TimetableItemDetailFloatingMenu.kt:103]: If the button background is transparent, the text will be difficult to read, so I have placed a black background.
