### PR TITLE
:wrench: We have fixed the locations where the old openURL method was being used.

### LINKED ISSUE #418: 【ComposeMultiplatform】Modify the navigate method of IosExternalNavController.
**Idea Description**

Tapping the “See More” button on EventMap does nothing.
The cause lies in the navigate method of IosExternalNavController.

```kotlin
UIApplication.sharedApplication.openURL(nsUrl)
```

UIApplication.openURL(_:) is deprecated in iOS 10 and later.
Because I attempted to use a deprecated method, Xcode only displays the following error log, and the process of opening links has stopped working.

```shell
BUG IN CLIENT OF UIKIT: The caller of UIApplication.openURL(_:) needs to migrate to the non-deprecated UIApplication.open(_:options:completionHandler:). Force returning false (NO).
```

As stated in the error message, modifying it to use `UIApplication.open(_:options:completionHandler:)` should make it work again.

**Reference images and links**

### PR DESCRIPTION
**Pull request by Corvus400**
## Issue
- close #418

## Overview (Required)
- The process for opening URLs has been fixed to function properly this fiscal year, just as it did last year.

## Links
- https://developer.apple.com/documentation/uikit/uiapplication/openurl(_:)
- https://developer.apple.com/documentation/uikit/uiapplication/open(_:options:completionhandler:)

## Movie (Optional)
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/4ed8e16f-2b0d-4086-85e6-a4f2f85159bd" width="300" > | <video src="https://github.com/user-attachments/assets/06984b56-980b-4956-9993-8881b0b99a9c" width="300" >

### CODE REVIEW

File: app-shared/src/iosMain/kotlin/io/github/droidkaigi/confsched/IosExternalNavController.kt [hunk 1]
```diff
@@ -34,11 +34,25 @@ actual fun rememberExternalNavController(): ExternalNavController {
...
+            println("Failed to navigate to URL (invalid URL): $url")
+            return
         }
+
+        if (!UIApplication.sharedApplication.canOpenURL(nsUrl)) {
+            println("Cannot open URL (scheme not allowed or no handler): $url")
+            return
+        }
+
+        UIApplication.sharedApplication.openURL(
```
Comment (Corvus400) [inline app-shared/src/iosMain/kotlin/io/github/droidkaigi/confsched/IosExternalNavController.kt:47]: Since the minimum deployment is iOS 18.4, we determined that fallback processing is unnecessary.

**Review by kitakkun — APPROVED** [review]
Looks perfect! Really appreciate your sincere contribution!
