### PR TITLE
Fix: surfaceTintDark color

### LINKED ISSUE #399: [Search Screen] Update the highlight color of the search results
**Idea Description**

The color settings in #372 were based on last year's Figma design, but the Figma has since been updated with this year's colors 🙏

Figma: https://www.figma.com/design/1YjyMBNVLEGcHP4W7UNzDE/DroidKaigi-2025-App-UI?node-id=57966-35285&t=7vBeqj6Y0uwYacAv-4

Color: D8E2FF （ tint 14%)

**Reference images and links**

### PR DESCRIPTION
**Pull request by YusukeSuzuki1213**
## Issue
- close #399 

## Overview (Required)
- Updated the color of surfaceTintDark to match Figma (ref: [Figma](https://www.figma.com/design/1YjyMBNVLEGcHP4W7UNzDE/DroidKaigi-2025-App-UI?node-id=57966-35285&t=kczAeM6Atri8iBin-0))

## Screenshot (Optional if screenshot test is present or unrelated to UI)
Before | After
:--: | :--:
 |

### CODE REVIEW

File: core/designsystem/src/commonMain/kotlin/io/github/droidkaigi/confsched/designsystem/theme/Colors.kt [hunk 1]
```diff
@@ -24,7 +24,7 @@ internal val surfaceDark = Color(0xFF111418)
 internal val onSurfaceDark = Color(0xFFE1E2E8)
 internal val surfaceVariantDark = Color(0xFF3F4849)
 internal val onSurfaceVariantDark = Color(0xFFBEC8C9)
-internal val surfaceTintDark = Color(0xFFAEC6FF)
+internal val surfaceTintDark = Color(0xFFD8E2FF)
```
Comment (YusukeSuzuki1213) [inline core/designsystem/src/commonMain/kotlin/io/github/droidkaigi/confsched/designsystem/theme/Colors.kt:27]: Alpha can be defined separately, as shown below:

https://github.com/DroidKaigi/conference-app-2025/blob/885fae295e7936b3ba87e06759ec923b4d674832/core/droidkaigiui/src/commonMain/kotlin/io/github/droidkaigi/confsched/droidkaigiui/session/TimetableItemCard.kt#L181

Comment (YusukeSuzuki1213) [reply core/designsystem/src/commonMain/kotlin/io/github/droidkaigi/confsched/designsystem/theme/Colors.kt:27]: I couldn’t find `0xFF1CE46B` anywhere else in the latest main branch. 
The color added in [#372](https://github.com/DroidKaigi/conference-app-2025/pull/372) seems to have been mostly removed in [#394](https://github.com/DroidKaigi/conference-app-2025/pull/394).

Comment (kilalabu) [reply core/designsystem/src/commonMain/kotlin/io/github/droidkaigi/confsched/designsystem/theme/Colors.kt:27]: I see. Thank you for your research.

**Review by kilalabu — APPROVED** [review]
Looks nice. Thank you for your work!!
